version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm run
          working_directory: ./client

workflows:
  build-and-test:
    jobs:
      - build-and-test